### ISSUE TITLE
from mmdet.apis import ... error

### ISSUE THREAD

**Issue by freja-zy** [FenHua/DetDak#5]
![image](https://user-images.githubusercontent.com/84123411/191532989-37ac691a-888b-4639-aac4-e1bd02be1f58.png)
请问一下这个该怎么办呢。改成from mmcv.runner import ...也不太行

**Comment by wmrenr** [comment]
应该是mmet版本的问题，你可以重装一下。

**Comment by michaelasare1** [comment]
Traceback (most recent call last):
  File "/home/test/Videos/DetDak/run0.py", line 9, in <module>
    from attack_utils.attackloss import ada_attack
  File "/home/test/Videos/DetDak/attack_utils/attackloss.py", line 3, in <module>
    from mmdet.apis import prepare_data  # 检测器
ImportError: cannot import name 'prepare_data' from 'mmdet.apis' (/home/test/anaconda3/lib/python3.9/site-packages/mmdet/apis/__init__.py)

I am also getting this error. I have reinstalled mmdet but i stll get the same error

Can I get some help here please @wangxueping78 @freja-zy @FenHua 

Thanks
